
package com.systec.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublishWebServiceService", targetNamespace = "http://main.systec.com/", wsdlLocation = "http://192.168.22.193:456/helloWord?wsdl")
public class PublishWebServiceService
    extends Service
{

    private final static URL PUBLISHWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLISHWEBSERVICESERVICE_EXCEPTION;
    private final static QName PUBLISHWEBSERVICESERVICE_QNAME = new QName("http://main.systec.com/", "PublishWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.22.193:456/helloWord?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLISHWEBSERVICESERVICE_WSDL_LOCATION = url;
        PUBLISHWEBSERVICESERVICE_EXCEPTION = e;
    }

    public PublishWebServiceService() {
        super(__getWsdlLocation(), PUBLISHWEBSERVICESERVICE_QNAME);
    }

    public PublishWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLISHWEBSERVICESERVICE_QNAME, features);
    }

    public PublishWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, PUBLISHWEBSERVICESERVICE_QNAME);
    }

    public PublishWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLISHWEBSERVICESERVICE_QNAME, features);
    }

    public PublishWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublishWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublishWebService
     */
    @WebEndpoint(name = "PublishWebServicePort")
    public PublishWebService getPublishWebServicePort() {
        return super.getPort(new QName("http://main.systec.com/", "PublishWebServicePort"), PublishWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublishWebService
     */
    @WebEndpoint(name = "PublishWebServicePort")
    public PublishWebService getPublishWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.systec.com/", "PublishWebServicePort"), PublishWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLISHWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PUBLISHWEBSERVICESERVICE_EXCEPTION;
        }
        return PUBLISHWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
